version:  '3'

services:
  api:
    image: node:14.18.0-alpine3.11
    container_name: calculator-api-marlon
    restart: always
    command: "npm run deploy"
    working_dir: /app
    volumes:
      - ./backend:/app
    ports:
      - '3333:3333'
  client:
    image: node:14.18.0-alpine3.11
    container_name: client-calculator-marlon
    restart: always
    command: "npm run start"
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - '3030:3030'