version:  '3'

services:
  api:
    image: node:16.16.0-alpine3.15
    container_name: api-marlon
    restart: always
    command: "npm run start"
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - '3333:3333'